spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/demo
    username: root
    password: rootpw
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      bindings:
        persistTransaction-in-0:
          destination: channel02

management:
  endpoints:
    web:
      exposure:
        include: health,info
